"""empty message

Revision ID: e40a2d3e9494
Revises: 
Create Date: 2024-03-21 18:14:45.598945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e40a2d3e9494'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=128), nullable=False),
    sa.Column('password', sa.CHAR(length=60), nullable=False),
    sa.Column('icon', sa.VARCHAR(length=64), nullable=True),
    sa.CheckConstraint("email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Z]{2,}$'"),
    sa.CheckConstraint('length(email) >= 5'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('finance',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('amount', sa.DECIMAL(scale=2), nullable=False),
    sa.Column('type', sa.Enum('Income', 'Outcome', name='expensetype'), nullable=False),
    sa.CheckConstraint('amount > 0'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finance_type'), 'finance', ['type'], unique=False)
    op.create_index(op.f('ix_finance_user_id'), 'finance', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_finance_user_id'), table_name='finance')
    op.drop_index(op.f('ix_finance_type'), table_name='finance')
    op.drop_table('finance')
    op.drop_table('user')
    # ### end Alembic commands ###
